💜 Implementing the backend API to the frontend
Breadkenty/Smash_Combos pull request #30
Opened 2020-09-02 06:10 UTC by Breadkenty

This is still incomplete but I wanted to get this out here for @sleeping-dev to help me with this comment I made on discord:

Although I do need help with one thing, and I'm a little too afraid to mess up the backend too much but I think how we do the GET for `Character` and `User` should change since these two refers to their `displayNames` to call them rather than its `Id`, it makes doing API calls for them a little complicated when I get objects that are nested in something like a `Combo` where it includes a `CharacterId`. To make it more simpler, is it possible to do a GET on both the `Id` and the `DisplayName`? I was looking at the Pokemon API(https://pokeapi.co/docs/v2#pokemon-section) for my students earlier today and noticed it can be done in the endpoints like this(https://pokeapi.co/api/v2/ability/{id or name}/), but would like a little help with making it happen.  I can go ahead and make a pull request for my changes I made on the controller and the core to take the `DisplayName` as the parameter for the GET Users so we can build on that. Also @Sleep#3174 I think this'll make it easier for me but I'm gonna make you a collaborator on the app, that way you have some powers to merge also.

I've already made some changed to the `UserControllers` to take the `displayName` for GET rather than the `id` so that our URL parameters wouldn't be `id` based eg. `smashcombos.com/user/Breadkenty` instead of `smashcombos.com/user/3`

2020-09-02 08:05 UTC, skittlz444 commented
The main thing I have against using display name in the url is duplication. If display names are enforced to be unique then there's no issue, but we'd have to force them to be unique, and to only contain url friendly characters.

2020-09-02 08:20 UTC, skittlz444 requested changes
Just a few changes to make the display name identification method more secure. Also you should make the column unique if it isn't already (don't have that up in front of me right now), this might mean removing some existing users that have doubled up already. Other than things for that it looks good!

2020-09-02 08:20 UTC, skittlz444 commented on Api/ClientApp/src/pages/User.jsx
> +  console.log(user)
Don't leave this log

2020-09-02 08:20 UTC, skittlz444 commented on Api/ClientApp/src/pages/User.jsx
>      console.log('Dismiss:')
Remove console logs

2020-09-02 08:20 UTC, skittlz444 commented on Api/ClientApp/src/pages/User.jsx
> +        console.log(apiData)
Remove console logs

2020-09-02 08:20 UTC, skittlz444 commented on Api/ClientApp/src/pages/User.jsx
> +    fetch(`/api/Characters/${characterVariableName}`)
I feel like this get characters function should be something exported from the characters component, this code shouldn't be duplicated into everywhere that needs to get a character.

2020-09-02 08:20 UTC, skittlz444 commented on Api/Controllers/UsersController.cs
> +            return User.Claims.FirstOrDefault(claim => claim.Type == "DisplayName").Value;
Use single or default, so I can't set my name to someone else's and get their data.

2020-09-02 08:20 UTC, skittlz444 commented on Smash_Combos.Core/Cqrs/Users/GetUser/GetUserRequestHandler.cs
>                          .FirstOrDefaultAsync();
Probably best to use single or default to get sensitive data like a user, we don't want to accidentally return the first if someone does something cheeky. Which is definately possible when using display name as the identifier.

2020-09-03 01:42 UTC, Breadkenty commented
I added the GetReportByDisplayName controller and also adding it to the CQRS. I made this so that getting a list of reports fo a user isn't so difficult on the front end lol. 

@skittlz444 Thanks for the feedback. I'll apply them before I am finished with this PR.

2020-09-03 05:37 UTC, Breadkenty commented
@sleeping-dev 

1. We’ve made a temporary fix to passing the character Object instead of its Id. This should be fixed. You've written a temporary fix for this by this code you wrote
```
 var user = await _dbContext.Users
                      .Include(user => user.Combos)
                          .ThenInclude(combo => combo.Reports)
                      .Include(user => user.Comments)
                          .ThenInclude(comment => comment.Reports)
                      .Include(user => user.Infractions)
                      .Where(user => user.DisplayName == request.DisplayName)
                      .FirstOrDefaultAsync();

            if (user == null)
                return null;



            var response = new GetUserResponse
            {
                Id = user.Id,
                DisplayName = user.DisplayName,
                UserType = user.UserType,
                Combos = new List<ComboDto>(),
                Comments = _mapper.Map<List<CommentDto>>(user.Comments),
                Infractions = _mapper.Map<List<InfractionDto>>(user.Infractions)
            };

            foreach (var combo in user.Combos)
            {
                var comboDto = _mapper.Map<ComboDto>(combo);
                var character = await _dbContext.Characters.Where(character => character.Id == combo.CharacterId).FirstOrDefaultAsync();
                comboDto.Character = _mapper.Map<CharacterDto>(character);
                response.Combos.Add(comboDto);
            }
            

            return response;
```

However this presented with another problem where the `Moderator` object is returning `null` so I changed it back temporarily. Id like to avoid getting Id's back for anything regarding `Users` (for `Moderator` and `Reporter`) and `Characters` so if you can help me with updating the backend would help me a ton here.

2. There's an object I'm missing that I would like to have when I `GET Report` which are the `Combo` and `Comment` associated with said `Report` This is because I'd like to link the content that the `Report` comes from. Refer to the `Reported Content` column in the screenshot.

![Screen Shot 2020-09-03 at 1 26 31 AM](https://user-images.githubusercontent.com/48931537/92074622-84574800-ed84-11ea-906b-e43d97f943a3.png)

3. This issue might be related to the first one but some of the comments where certain comments are returning a null `User` object. It's looking like it's returning `User` Objects only if the `Combo.User.DisplayName` and the `Comment.User.DisplayName` matches
![Screen Shot 2020-09-01 at 9 59 06 PM](https://user-images.githubusercontent.com/48931537/92074757-de580d80-ed84-11ea-8f54-3f5ee9237720.png)

4. I've already started to work on this, but ideally I'd like all `GET` requests for `Users`, "Infractions", "Reports", and `Characters` to be by the `DisplayName`/ `VariableName` instead of `Id`. 
- Get `User` by `DisplayName`
- Get `Character` by `VariableName`
- Get `Reports` by `DisplayName` (get all reports by a given user)
- Get `Infractions` by `DisplayName (get all infractions by a given user) 

These are all the things I can think of right now at least for GETs. I know I'll come across some stuff with POSTs and PUTs but we'll work on that when we get there. Any help with this would be great.

2020-09-03 17:53 UTC, sleeping-dev commented
Alright @Breadkenty, bullet points 1-3 should be fixed/added. I added the Character object reference to Combos & fixed some missing .Include() statements so now everything should be loaded correctly.

I'll take a break now and see if I can fix the rest after dinner so you have everything you need frontend-wise.

2020-09-03 17:59 UTC, sleeping-dev commented
I had an idea for handling the communication between the core and the API Controllers a bit better and implemented it for the Combo-Methods as a test. Would love a review on it @skittlz444, if it breaks the pattern or is faulty in other ways:

Basically I introduced a `ResponseBase` class with a Generic `Data` property to hold the response data, and a `ResponseStatus` and `ResponseMessage` property so we can deal with the Core-Responses in the API Controllers in a cleaner way. Before I was putting booleans in the responses, or checking for null, etc, this would be a nice streamlined way of going about things. What do you think?

2020-09-03 19:45 UTC, sleeping-dev commented
This should take care of everything you requested Kento, let me know if anything's missing.

2020-09-04 04:45 UTC, Breadkenty commented
@sleeping-dev Awesome job bud! I made a couple of commits to work off what you've done so far. As I was working on this, I was thinking of something that I want to run by you. 

Should we add a dismiss property for the Infraction model? I'm thinking this would be used in the following scenario:

1. A moderator wrongfully infracts a user
2. A user appealed their infraction by contacting the admins
3. The admins look at the user's infraction that was given by the moderator
4. Admins realize that the user was wrongfully infracted, therefore dismissing the infraction
5. The infraction will be on record just in case we come across another issue with the same exact user if they commit another offense
6. Address the issue with moderators to prevent abusive use of their power

For this reason, I went ahead and added the dismiss button on infractions. Let me know what you think. For the most part, I think everything in regards to GET is done with my recent commit. The next thing I'll work on is the ability to:
1. Create a report on comment/combo
2. Create an infraction
3. Dismiss infraction/report
4. Unban a user
5. Limiting the report UI to moderators and admins

My goal to get it done by Weds went right out the window but we'll get it done by this Sunday at the latest at this rate!

2020-09-04 04:48 UTC, Breadkenty commented
@skittlz444 @skittlz444 Oh and one more thing. We had an issue with using `SingleOrDefault` specifically for the GET `User/DisplayName`. For the time being, I went ahead and switched it back to `FirstOrDefault` but if you can find the solution to it, that would be great. This was the error I was getting:
![Screen Shot 2020-09-03 at 9 55 51 PM](https://user-images.githubusercontent.com/48931537/92200576-415ea880-ee48-11ea-9a8f-b0f108c586f8.png)

2020-09-04 09:09 UTC, sleeping-dev commented
I believe exception that's being thrown here is working as intended, could it be that you have multiple users with the same name in your database? It worked fine for me, but I just tried it while having two users with the same name and got the same exception. So this should be working as intended, we just need to surround it with a try-catch to catch the exception and react accordingly, I'll whip that up real quick.

2020-09-04 09:27 UTC, sleeping-dev commented
@Breadkenty Yes, the comment thing is because when submitting the comment the email-field is missing:
```
  const [comment, setComment] = useState({
    comboId: parseInt(comboId),
    user: { // Email should be in here
      displayName: loggedInUser.displayName, 
    },
    body: '',
  })
```

This will fix itself when we move the Comment-Methods to the core and use CQRS, I don't have time to do it right now but I'll to id later today.

2020-09-05 01:22 UTC, Breadkenty commented
@sleeping-dev You're completely right it was that I had multiple users with the same `DisplayName`, which is weird because I didn't create them and you shouldn't be able to create a user with an existing display name. Not sure how it got there. I'll have to look into this further later.

2020-09-06 06:17 UTC, sleeping-dev commented
I didn't realize that you wanted everything to go by the DisplayName. If we commit to having the DisplayName be the main property to determine users by, we might as well make it the primary key in the database, that way we can ensure that there's no double users. Then we could even remove the Id...

2020-09-06 19:13 UTC, Breadkenty reviewed
@sleeping-dev For the sake of confusion we should probably rename these

2020-09-07 07:00 UTC, sleeping-dev commented on Smash_Combos.Core/Cqrs/Combos/PutCombo/PutComboRequest.cs
> +        public string CharacterName { get; set; }
Done

2020-09-07 07:00 UTC, sleeping-dev commented on Smash_Combos.Core/Cqrs/Combos/PutCombo/PutComboRequestHandler.cs
> +            var character = await _dbContext.Characters.Where(character => character.VariableName == request.CharacterName).FirstOrDefaultAsync();
Done

2020-09-09 06:40 UTC, Breadkenty commented
Everything on the frontend should be up to date, all we're waiting for now is the error messages with the requests. 

Couple things I'd like to request changes in the backend:
1. Reports and Comments body shouldn’t be nullable
2. POST Sessions to return an error message if a user is banned. `User is currently banned for: [insert infraction body here]`
3. POST Infraction to dismiss all existing non-dismissed reports
4. Reports can only be made once by the user
5. Prevent mods/admins from warning/ban/infracting themselves. 
6. Prevent mods/admins from dismissing their own reports. (Hopefully, another mod will keep other mods in check)

@skittlz444 I'm so sorry that this PR is HUGE! I didn't think about how to split this into bite-size chunks, but I know for next time. We're almost at the finish line for this feature!

2020-09-09 07:26 UTC, skittlz444 commented
No need to apologise! You guys have been doing heaps of great work. I have to apologise though, with everything happening with me at the moment I really don't have enough time to review it all, I had a look at a few request handlers, controllers etc and after the problem detail pr is in here and a good full systems test is done to iron out the bugs then its probably good to go. The structure is there, I'll trust you guys for the details.

2020-09-12 21:33 UTC, merged